# Generated by Django 4.2.23 on 2025-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('minimal_dark', 'Minimal Dark'), ('creative_burst', 'creative_burst'), ('modern_light', 'Modern_light'), ('gradient_showcase', 'gradient_showcase'), ('tech_noir', 'tech_noir'), ('professional_corporate', 'professional_corporate')], default='minimal_dark', max_length=50),
        ),
    ]
