# Generated by Django 4.2.23 on 2025-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='behance_url',
            field=models.URLField(blank=True),
        ),
    ]
